# name: Code Review

# permissions:
#   contents: read
#   pull-requests: write

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

# jobs:
#   code_review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: ChatGPT Code Review
#         uses: anc95/ChatGPT-CodeReview@main
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#           MODEL: text-davinci-002
#           LANGUAGE: Chinese
#           top_p: 0.5
#           temperature: 0.5

#       - name: ChatGTP explain code
#         uses: cirolini/chatgpt-github-actions@v1.3
#         with:
#           openai_api_key: ${{ secrets.OPENAI_API_KEY }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           github_pr_id: ${{ github.event.number }}
#           openai_engine: 'text-davinci-002' #optional
#           openai_temperature: 0.5 #optional
#           openai_max_tokens: 2048 #optional
#           mode: file # file or patch

# name: Code Review

# permissions:
#   contents: read
#   pull-requests: write

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           repository: ${{github.event.pull_request.head.repo.full_name}}
#           ref: ${{github.event.pull_request.head.ref}}
#           submodules: false

#       - uses: unsafecoerce/chatgpt-action@main
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CHATGPT_ACCESS_TOKEN: ${{ secrets.CHATGPT_ACCESS_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#         with:
#           debug: true
#           action: score

#       - uses: unsafecoerce/chatgpt-action@main
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CHATGPT_ACCESS_TOKEN: ${{ secrets.CHATGPT_ACCESS_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#         with:
#           debug: true
#           action: review
#           review_comment_lgtm: true

name: Chat GPT Review

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

env:
  PROMPT: 'Hello, can you tell me what is the meaning of life?'

jobs:
  generateResponse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn add axios
      - name: Generate response
        id: generate-response
        run: |
          response=$(curl https://api.openai.com/v1/completions \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "{
              \"prompt\": \"${{ env.PROMPT }}\",
              \"max_tokens\": 1024,
              \"temperature\": 0.5,
              \"model\": \"text-davinci-003\"
            }")
          echo "Response data: $response"
          echo "::set-output name=response-data::$response"
          # echo "RESPONSE=$response" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  comment-on-pr:
    needs: generateResponse
    runs-on: ubuntu-latest
    steps:
      - name: Get response data from generateResponse
        id: get-response-data
        run: |
          echo "Output: ${JSON.stringify(needs.generateResponse.outputs)}}"
          echo "getResponseData: ${{ needs.generateResponse.outputs.response-data }} ${{needs.generateResponse.outputs}}"
          echo "::set-output name=response-data::${{ needs.generateResponse.outputs.response-data }}"
      - name: Post comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('responseData', '${{ steps.get-response-data.outputs.response-data }}')
            const response = JSON.parse('${{ steps.get-response-data.outputs.response-data }}');
            # console.log('env: ${{ env }}')
            # console.log('RESPONSE_ENV: ${{ env.RESPONSE }}')
            # const response = JSON.parse('${{ env.RESPONSE }}');
            console.log('response', response)
            const comment = `Generated response: ${response.choices[0].text || response.completions[0].text}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
