# name: Chat GPT Review

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
env:
  PROMPT: 'Hello, can you tell me what is the meaning of life?'

jobs:
  generateResponse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn add axios
      - name: Generate response
        id: generate-response
        run: |
          response=$(curl https://api.openai.com/v1/completions \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "{
              \"prompt\": \"${{ env.PROMPT }}\",
              \"max_tokens\": 1024,
              \"temperature\": 0.5,
              \"model\": \"text-davinci-003\"
            }")
          echo "::set-output name=response-data::$response"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
